Sistema_mapeamento_laboratorio-main/gestor/urls.py
from django.urls import path
from . import views
from .views import calendario_reservas
from .views import calendario_reservas_materiais
from .views import reservas_materiais
from .views import reservas_salas
from .views import SalaListView, SalaCreateView, SalaUpdateView, SalaDetailView, SalaDeleteView
from .views import MaterialListView, MaterialCreateView, MaterialUpdateView, MaterialDetailView, MaterialDeleteView



app_name = 'gestor'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('gestor_ver_salas/', views.gestor_ver_salas, name='gestor_ver_salas'),
    path('gestor_ver_materiais/', views.gestor_ver_materiais, name='gestor_ver_materiais'),
    path('calendario_reservas/', calendario_reservas, name='calendario_reservas'),
    path('calendario_reservas_materiais/', calendario_reservas_materiais, name='calendario_reservas_materiais'),
    path('reservas_materiais/', reservas_materiais, name='reservas_materiais'),
    path('reservas_salas/', reservas_salas, name='reservas_salas'),
    path('salas/', SalaListView.as_view(), name='sala_list'),
    path('salas/nova/', SalaCreateView.as_view(), name='sala_create'),
    path('salas/<int:pk>/editar/', SalaUpdateView.as_view(), name='sala_edit'),
    path('salas/<int:pk>/detail/', SalaDetailView.as_view(), name='sala_detail'),
    path('salas/<int:pk>/excluir/', SalaDeleteView.as_view(), name='sala_delete'),
     path('materiais/', MaterialListView.as_view(), name='material_list'),
    path('materiais/novo/', MaterialCreateView.as_view(), name='material_create'),
    path('materiais/<int:pk>/editar/', MaterialUpdateView.as_view(), name='material_edit'),
    path('materiais/<int:pk>/detalhes/', MaterialDetailView.as_view(), name='material_detail'),
    path('materiais/<int:pk>/excluir/', MaterialDeleteView.as_view(), name='material_delete')
]

Sistema_mapeamento_laboratorio-main/salas/urls.py
from django.urls import path
from . import views

app_name = 'salas'

urlpatterns = [
    path('home/', views.home, name = 'home')
]

Sistema_mapeamento_laboratorio-main/sistema/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('usuarios.urls')),
    path('professor/', include('professor.urls')),
    path('salas/', include('salas.urls')),
    path('materiais/', include('materiais.urls')),
    path('gestor/', include('gestor.urls')),
]

Sistema_mapeamento_laboratorio-main/materiais/models.py
from django.db import models
from datetime import date

from django.forms import ValidationError
from usuarios.models import Usuario

class Materiais(models.Model):
    nome_do_material = models.CharField(max_length=30)
    reservado = models.BooleanField(default=False)
    
    class Meta:
        verbose_name = 'Material'

    def __str__(self):
        return self.nome_do_material

class Reserva(models.Model):
    usuarios = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING)
    data_reserva = models.DateTimeField()
    data_devolucao = models.DateTimeField()
    data_solicitacao = models.DateTimeField(auto_now_add=True)
    materiais = models.ForeignKey(Materiais, on_delete=models.DO_NOTHING)
    
    class Meta:
        verbose_name = 'Reserva'
    
    def __str__(self) -> str:
        return f"{self.usuarios} | {self.materiais}"

    def clean(self):
         # Certifique-se de que materiais, data_reserva e data_devolucao não são None
        if self.materiais is None or self.data_reserva is None or self.data_devolucao is None:
           raise ValidationError('Materiais, data de reserva e data de devolução devem ser fornecidos.')

        # Verifica se já existe uma reserva para o mesmo material no mesmo horário
        conflito = Reserva.objects.filter(
            materiais=self.materiais,
            data_reserva__lt=self.data_devolucao,
            data_devolucao__gt=self.data_reserva
        ).exists()

        if conflito:
            raise ValidationError('Já existe uma reserva para este material no horário selecionado.')

    def save(self, *args, **kwargs):
        self.clean()
        return super(Reserva, self).save(*args, **kwargs)

Sistema_mapeamento_laboratorio-main/salas/models.py
# from django.db import models
# from datetime import date
# from usuarios.models import Usuario

# class Salas(models.Model):
#     UABJ = 'UABJ'
#     AEB = 'AEB'
#     LOCAL_CHOICES = [
#         (UABJ, 'UABJ'),
#         (AEB, 'AEB'),
#     ]

#     nome_da_sala = models.CharField(max_length=30)
#     local = models.CharField(max_length=4, choices=LOCAL_CHOICES, default=UABJ)
#     reservado = models.BooleanField(default=False)
    
#     class Meta:
#         verbose_name = 'Sala'

#     def __str__(self):
#         return f"{self.nome_da_sala} ({self.get_local_display()})"  # Retorna nome da sala e local formatados

# class Reservas(models.Model):
#     usuarios = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING)
#     data_reserva = models.DateTimeField()
#     data_devolucao = models.DateTimeField()
#     data_solicitacao = models.DateTimeField(auto_now_add=True)
#     salas = models.ForeignKey(Salas, on_delete=models.DO_NOTHING)
    
#     class Meta:
#         verbose_name = 'Reserva'
    
#     def __str__(self):
#         return f"{self.usuarios} | {self.salas}"

from django.db import models
from django.core.exceptions import ValidationError
from datetime import date
from usuarios.models import Usuario

class Salas(models.Model):
    UABJ = 'UABJ'
    AEB = 'AEB'
    LOCAL_CHOICES = [
        (UABJ, 'UABJ'),
        (AEB, 'AEB'),
    ]

    nome_da_sala = models.CharField(max_length=30)
    local = models.CharField(max_length=4, choices=LOCAL_CHOICES, default=UABJ)
    reservado = models.BooleanField(default=False)
    
    class Meta:
        verbose_name = 'Sala'

    def __str__(self):
        return f"{self.nome_da_sala} ({self.get_local_display()})"  # Retorna nome da sala e local formatados

class Reservas(models.Model):
    usuarios = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING)
    data_reserva = models.DateTimeField()
    data_devolucao = models.DateTimeField()
    data_solicitacao = models.DateTimeField(auto_now_add=True)
    salas = models.ForeignKey(Salas, on_delete=models.DO_NOTHING)
    
    class Meta:
        verbose_name = 'Reserva'
    
    def __str__(self):
        return f"{self.usuarios} | {self.salas}"

    def clean(self):
        # Certifique-se de que materiais, data_reserva e data_devolucao não são None
        if self.salas is None or self.data_reserva is None or self.data_devolucao is None:
            raise ValidationError('Salas, data de reserva e data de devolução devem ser fornecidos.')

        # Verifica se já existe uma reserva para o mesmo material no mesmo horário
        conflito = Reservas.objects.filter(
            salas=self.salas,
            data_reserva__lt=self.data_devolucao,
            data_devolucao__gt=self.data_reserva
        ).exists()

        if conflito:
            raise ValidationError('Já existe uma reserva para este material no horário selecionado.')

   

       

    def save(self, *args, **kwargs):
        self.clean()
        return super(Reservas, self).save(*args, **kwargs)

Sistema_mapeamento_laboratorio-main/gestor/forms.py
from django import forms
from .models import Salas
from .models import Materiais

class SalaForm(forms.ModelForm):
    class Meta:
        model = Salas
        fields = ['nome_da_sala', 'local']  
        
class MaterialForm(forms.ModelForm):
    class Meta:
        model = Materiais
        fields = ['nome_do_material'] 

Sistema_mapeamento_laboratorio-main/gestor/views.py
# Importando as bibliotecas necessárias
from datetime import timezone
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from gestor.forms import MaterialForm, SalaForm
from materiais.models import Materiais, Reserva
from usuarios.models import Usuario
from salas.models import Salas
from salas.models import Reservas
from itertools import groupby
from django.contrib import messages
from django.shortcuts import render
from django.db.models import F
from itertools import groupby
from .models import Reserva
from django.utils import timezone


def home(request):
    # Verifica se há um usuário na sessão
    if request.session.get('usuario'):
        try:
            # Tenta obter o objeto de usuário com base no ID armazenado na sessão
            usuario = Usuario.objects.get(id=request.session['usuario'])

            # Cria um contexto para ser passado para o template
            context = {
                'usuario': usuario,          # Objeto de usuário
                'nome_usuario': usuario.nome, # Atributo 'nome' do usuário
                'salas': Salas.objects.all(),   # Obtém todas as instâncias do modelo Salas
                'usuario_logado2': usuario,
            }

            # Renderiza o template 'home.html' com o contexto
            return render(request, 'home.html', context)
        
        except Usuario.DoesNotExist:
            # Trata o caso em que o usuário não existe
            return render(request, 'error.html', {'message': 'Usuário não existe'})

    else:
        # Redireciona para a página de login se não houver usuário na sessão
        return redirect('/auth/login/?status=2')
    
# Função para o gestor visualizar as salas

def gestor_ver_salas(request):
    # Verifica se há um usuário na sessão
    if request.session.get('usuario'):
        try:
            # Tenta obter o objeto de usuário com base no ID armazenado na sessão
            usuario = Usuario.objects.get(id=request.session['usuario'])

            # Cria um contexto para ser passado para o template
            context = {
                'usuario': usuario,             # Objeto de usuário
                'nome_usuario': usuario.nome,   # Atributo 'nome' do usuário
                'salas': Salas.objects.all(),   # Obtém todas as instâncias do modelo Salas
                'usuario_logado2': usuario
            }

            return render(request, 'gestor_ver_salas.html', context)

        except Usuario.DoesNotExist:
            # Trata o caso em que o usuário não existe
            return render(request, 'error.html', {'message': 'Usuário não existe'})
    else:
        # Redireciona para a página de login se não houver usuário na sessão
        return redirect('/auth/login/?status=2')

def gestor_ver_materiais(request):
    if request.session.get('usuario'):
        try:
            usuario = Usuario.objects.get(id=request.session['usuario'])

            context = {
                'usuario': usuario,
                'nome_usuario': usuario.nome,
                'materiais': Materiais.objects.all(),
                'usuario_logado2': usuario
            }

            return render(request, 'gestor_ver_materiais.html', context)
        except Usuario.DoesNotExist:
            # Trata o caso em que o usuário não existe
            return render(request, 'error.html', {'message': 'Usuário não existe'})
    else:
        # Redireciona para a página de login se não houver usuário na sessão
        return redirect('/auth/login/?status=2')

#Função para exibir calendario salas-Tabela
def calendario_reservas(request):
    if request.session.get('usuario'):
        try:
            usuario = Usuario.objects.get(id=request.session['usuario'])
            reservas = Reservas.objects.all()
            reservas_ordenadas = sorted(reservas, key=lambda x: x.data_reserva)
            grupos_por_data = {data: list(grupo) for data, grupo in groupby(reservas_ordenadas, key=lambda x: x.data_reserva)}

            eventos = []

            for data, reservas_na_data in grupos_por_data.items():
                eventos_na_data = []
                for reserva in reservas_na_data:
                    # Converte a data de reserva e a data de devolução para o fuso horário desejado
                    data_reserva = reserva.data_reserva.astimezone(timezone.get_default_timezone())
                    data_devolucao = reserva.data_devolucao.astimezone(timezone.get_default_timezone())
                    data_solicitacao = reserva.data_solicitacao.astimezone(timezone.get_default_timezone())

                    evento = {
                        'title': f"Reserva por {reserva.usuarios.nome} - {reserva.salas.nome_da_sala}",
                        'start': data_reserva.strftime("%d/%m/%Y %H:%M" ),
                        'end': data_devolucao.strftime("%d/%m/%Y %H:%M" ),  # Formata a data de devolução corretamente
                        'url': f'/calendario_reservas.html/{reserva.id}',  # Substitue com a URL correta para detalhes da reserva
                        'data_solicitacao': data_solicitacao.strftime("%d/%m/%Y %H:%M") if reserva.data_solicitacao else None,
                    }
                    eventos_na_data.append(evento)
                eventos.append({'data': data.strftime("%d/%m/%Y"), 'eventos': eventos_na_data})

            return render(request, 'calendario_reservas.html', {'eventos': eventos, 'usuario_logado2': usuario})

        except Usuario.DoesNotExist:
            messages.error(request, 'Usuário não encontrado.')
            return render(request, 'error.html', {'message': 'Usuário não existe'})
    else:
        messages.warning(request, 'Faça login para acessar o calendário de reservas.')
        return redirect('/auth/login/?status=2')



# Função para exibir o calendário de reservas de materiais
def calendario_reservas_materiais(request):
    if request.session.get('usuario'):
        try:
            usuario = Usuario.objects.get(id=request.session['usuario'])

            # Obtenha todas as reservas de materiais do banco de dados
            reservas_materiais = Reserva.objects.filter(materiais__isnull=False)

            # Ordene as reservas por data de reserva
            reservas_ordenadas = sorted(reservas_materiais, key=lambda x: x.data_reserva)

            # Agrupe as reservas por data de reserva
            grupos_por_data = {data: list(grupo) for data, grupo in groupby(reservas_ordenadas, key=lambda x: x.data_reserva)}

            # Crie uma lista para armazenar os eventos do calendário de materiais
            eventos_materiais = []

            for data, reservas_na_data in grupos_por_data.items():
                eventos_na_data = []
                for reserva in reservas_na_data:
                    # Converte a data de reserva e a data de devolução para o fuso horário desejado
                    data_reserva = reserva.data_reserva.astimezone(timezone.get_default_timezone())
                    data_devolucao = reserva.data_devolucao.astimezone(timezone.get_default_timezone())
                    data_solicitacao = reserva.data_solicitacao.astimezone(timezone.get_default_timezone())


                    evento_material = {
                        'title': f"Reserva de Material por {reserva.usuarios.nome} - {reserva.materiais.nome_do_material}",
                        'start': data_reserva.strftime("%d/%m/%Y %H:%M"),
                        'end': data_devolucao.strftime("%d/%m/%Y %H:%M"),
                        'url': f'/calendario_reservas_materiais.html/{reserva.id}',
                        'data_solicitacao': data_solicitacao.strftime("%d/%m/%Y %H:%M" ) if reserva.data_solicitacao else None,
                        'tipo_reserva': 'Material',  # Indica que é uma reserva de material
                    }
                    eventos_na_data.append(evento_material)
                eventos_materiais.append({'data': data.strftime("%d/%m/%Y"), 'eventos': eventos_na_data})

            return render(request, 'calendario_reservas_materiais.html', {'eventos_materiais': eventos_materiais, 'usuario_logado2': usuario})

        except Usuario.DoesNotExist:
            messages.error(request, 'Usuário não encontrado.')
            return render(request, 'error.html', {'message': 'Usuário não existe'})
    else:
        messages.warning(request, 'Faça login para acessar o calendário de reservas.')
        return redirect('/auth/login/?status=2')
    
def reservas_materiais(request):
    if request.session.get('usuario'):
        try:
            usuario = Usuario.objects.get(id=request.session['usuario'])
            reservas = Reserva.objects.all()

            # Ordene as reservas por data de reserva
            reservas_ordenadas = reservas.order_by('data_reserva')

            # Agrupe as reservas por data de reserva
            grupos_por_data = {data: list(grupo) for data, grupo in groupby(reservas_ordenadas, key=lambda x: x.data_reserva)}

            eventos_mat = []

            for data, reservas_na_data in grupos_por_data.items():
                for reserva in reservas_na_data:
                    # Adicione o nome do usuário ao título do evento
                    evento_material = {
                        'title': f"Reserva de {reserva.usuarios.nome} - {reserva.materiais.nome_do_material}",
                        'start': reserva.data_reserva.isoformat(),
                        # 'end': reserva.data_devolucao.isoformat(),
                    }
                    eventos_mat.append(evento_material)

            return render(request, 'reservas_materiais.html', {'eventos_mat': eventos_mat, 'usuario_logado2': usuario})
        except Reserva.DoesNotExist:

Sistema_mapeamento_laboratorio-main/salas/views.py
from django.shortcuts import render
from django.http import HttpResponse

def home(request):
    return HttpResponse('Olá')

Sistema_mapeamento_laboratorio-main/gestor/templates/home.html
{% extends 'base.html' %}

{% block 'titulo' %}
    Home
{% endblock %}

{% block 'conteudo' %}

<div class="container">
    <br>
    <br>

    <!-- Título principal da página -->
    <h1 class="display-4">Sistema de Mapeamento de Materiais
        <hr style="display: block;">
    </h1>

    <!-- Saudação ao administrador -->
    <p class="lead">
        <!-- Ícone de casa seguido da mensagem de boas-vindas -->
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house"
            viewBox="0 0 16 16">
            <path
                d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5ZM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5 5 5Z" />
        </svg>
        Olá, seja bem vindo, você está logado como ADMINISTRADOR!
    </p>

    <!-- Row principal -->
    <div class="row">
        <!-- Coluna para as Salas -->
        <div class="col-md-6">
            <!-- Card para as Salas -->
            <div class="card mt-4">
                <div class="card-body">
                    <h5 class="card-title">Salas</h5>
                    <p class="card-text">Aqui você pode ver todas as salas cadastradas no sistema.</p>
                    <a href="{% url 'gestor:gestor_ver_salas' %}" class="btn btn-primary">Ver salas</a>
                </div>
            </div>

            <!-- Card para a tabela de Reservas de Salas -->
            <div class="card mt-4">
                <div class="card-body">
                    <h5 class="card-title">Tabela de Reservas de Salas</h5>
                    <p class="card-text">Veja as reservas das Salas na tabela.</p>
                    <a href="{% url 'gestor:calendario_reservas' %}" class="btn btn-primary">Ver Tabela</a>
                </div>
            </div>

            <!-- Card para o calendário de Reservas de Salas -->
            <div class="card mt-4">
                <div class="card-body">
                    <h5 class="card-title"> Calendário de Reservas de Salas</h5>
                    <p class="card-text">Veja as reservas das Salas no calendário.</p>
                    <a href="{% url 'gestor:reservas_salas' %}" class="btn btn-primary">Ver Calendário</a>
                </div>
            </div>

            <!-- Card para o Cadastro de Salas -->
            <div class="card mt-4">
                    <div class="card-body">
                        <h5 class="card-title">Cadastro de Salas</h5>
                        <p class="card-text">Cadastar/Editar/Apagar Salas.</p>
                        <a href="{% url 'gestor:sala_list' %}" class="btn btn-primary">Cadastrar Salas</a>
                    </div>
            </div>
        </div>

        <!-- Coluna para os Materiais -->
        <div class="col-md-6">
            <!-- Card para os Materiais -->
            <div class="card mt-4">
                <div class="card-body">
                    <h5 class="card-title">Materiais</h5>
                    <p class="card-text">Aqui você pode ver todos materiais cadastrados no sistema.</p>
                    <a href="{% url 'gestor:gestor_ver_materiais' %}" class="btn btn-primary">Ver materiais</a>
                </div>
            </div>

            <!-- Card para a tabela de Reservas de Materiais -->
            <div class="card mt-4">
                <div class="card-body">
                    <h5 class="card-title">Tabela de Reservas de Materiais</h5>
                    <p class="card-text">Veja as reservas dos Materiais na tabela.</p>
                    <a href="{% url 'gestor:calendario_reservas_materiais' %}" class="btn btn-primary">Ver Tabela</a>
                </div>
            </div>

            <!-- Card para o calendario de Reservas de Materiais -->
            <div class="card mt-4">
                <div class="card-body">
                    <h5 class="card-title">Calendário Reservas de Materiais</h5>
                    <p class="card-text">Veja as reservas dos Materiais no calendário.</p>
                    <a href="{% url 'gestor:reservas_materiais' %}" class="btn btn-primary">Ver Calendário</a>
                </div>
            </div>

            <!-- Card para o cadastro de materiais-->
            <div class="card mt-4">
                    <div class="card-body">
                        <h5 class="card-title">Cadastro de Materiais</h5>
                        <p class="card-text">Cadastar/Editar/Apagar Materiais.</p>
                        <a href="{% url 'gestor:material_list' %}" class="btn btn-primary">Cadastrar Materiais</a>
                    </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Sistema_mapeamento_laboratorio-main/gestor/templates/material_detail.html
{% extends 'base.html' %}

{% block 'titulo' %}Materiais Cadastrados{% endblock %}

{% block 'conteudo' %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Visualizar Material</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #fff; /* Fundo branco para a página */
            color: #333; /* Texto preto */
            padding: 20px;
        }

        input[type="submit"] {
            background-color: #d9534f; /* Vermelho */
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            margin-bottom: 20px;
        }

        input[type="submit"]:hover {
            background-color: #c9302c;
        }

        h1 {
            color: #fff;
            text-align: center; /* Centraliza o título */
            margin-top: 0; /* Remove margem superior padrão do h1 */
        }

        .conteudo {
            max-width: 500px;
            margin: 0 auto;
            background-color: #1f3154; /* Fundo azul para a seção de conteúdo */
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            color: #fff; /* Texto branco para contrastar */
        }

        .info {
            margin-bottom: 10px;
        }

        .info label {
            font-weight: bold;
        }

        .info span {
            margin-left: 10px;
        }

    </style>
</head>

<body>
    <input type="submit" onclick="location.href = '{% url 'gestor:material_list' %}'" value="Materiais Cadastrados"
        title="Clique para voltar para a lista de Materiais Cadastrados">
    <div class="conteudo">
        <h1>Detalhes do Material:</h1>
        <div class="info">
            <label for="nome_material">Nome do Material:</label>
            <span id="nome_material">{{ object.nome_do_material }}</span>
        </div>
    </div>
</body>

</html>

{% endblock %}

Sistema_mapeamento_laboratorio-main/gestor/templates/material_form.html
{% extends 'base.html' %}

{% block 'titulo' %}Material Cadastrados{% endblock %}

{% block 'conteudo' %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Criar Material</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5; /* Cor de fundo original */
            color: #333; /* Cor do texto original */
            padding: 20px;
        }

        h1 {
            color: #333;
            text-align: center;
            margin-bottom: 20px; /* Adicionado espaçamento abaixo do título */
        }

        form {
            max-width: 500px;
            margin: 0 auto;
            background-color: #1f3154; /* Fundo azul para o formulário */
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }

        .form-group {
            margin-bottom: 20px;
        }

        label {
            display: block;
            font-weight: bold;
            margin-bottom: 5px;
            color: #fff; /* Cor do texto do label */
        }

        input[type="text"],
        input[type="submit"],
        input[type="reset"] {
            width: 100%;
            padding: 10px;
            border-radius: 3px;
            border: 1px solid #ccc;
            box-sizing: border-box;
            font-size: 16px;
        }

        input[type="text"] {
            margin-bottom: 10px;
        }

        input[type="submit"] {
            background-color: #5cb85c; /* Verde */
            color: #fff;
            border: none;
            cursor: pointer;
        }

        input[type="submit"]:hover {
            background-color: #4cae4c;
        }

        input[type="reset"] {
            background-color: #d9534f; /* Vermelho */
            color: #fff;
            border: none;
            cursor: pointer;
            margin-right: 10px;
        }

        input[type="reset"]:hover {
            background-color: #c9302c;
        }

        /* Tooltip para o campo de entrada 'Nome do Material' */
        input[type="text"]#id_nome_do_material::placeholder {
            color: #aaa;
        }

        input[type="text"]#id_nome_do_material:hover::placeholder {
            color: #666;
        }

        input[type="text"]#id_nome_do_material:focus::placeholder {
            color: #333;
        }

    </style>
</head>

<body>
    <h1>Inserindo cadastro de Materiais</h1>
    <form method="post" action=".">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_nome_do_material">Nome do Material:</label>
            <input type="text" name="nome_do_material" id="id_nome_do_material"
                placeholder="Digite aqui o nome do material" required>
        </div>
        <input type="submit" value="Salvar"><input type="reset" value="Cancelar"
            onclick="location.href = '{% url 'gestor:material_list' %}'">
    </form>
</body>

</html>
{% endblock %}