Sistema_mapeamento_laboratorio-main/professor/urls.py
from django.urls import path
from . import views

app_name = 'professor'

urlpatterns = [
    path('homee/', views.homee, name='homee'),
    path('ver_salas_professor/<int:id>', views.ver_salas_professor, name='ver_salas_professor'),
    path('realizar_reserva_salas/', views.realizar_reserva_salas, name='realizar_reserva_salas'),
    path('ver_materiais_professor/<int:id>', views.ver_materiais_professor, name='ver_materiais_professor'),
    path('realizar_reserva_materiais/', views.realizar_reserva_materiais, name='realizar_reserva_materiais'),
    path('reserva_sucesso/', views.reserva_sucesso, name='reserva_sucesso'),
    path('reserva_dados_invalidos/', views.reserva_dados_invalidos, name='reserva_dados_invalidos'),
]

Sistema_mapeamento_laboratorio-main/salas/urls.py
from django.urls import path
from . import views

app_name = 'salas'

urlpatterns = [
    path('home/', views.home, name = 'home')
]

Sistema_mapeamento_laboratorio-main/sistema/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('usuarios.urls')),
    path('professor/', include('professor.urls')),
    path('salas/', include('salas.urls')),
    path('materiais/', include('materiais.urls')),
    path('gestor/', include('gestor.urls')),
]

Sistema_mapeamento_laboratorio-main/professor/models.py
from django.db import models
from salas.models import Salas, Reservas
from .forms import RealizarReservas
from materiais.models import Materiais, Reserva
from .forms import RealizarReserva
from usuarios.models import Usuario
from .validators import validate_date_not_past 
from django.core.exceptions import ValidationError



def validate_date_not_past(date):
    if date < timezone.now().date():
        raise ValidationError("A data não pode ser no passado!")

Sistema_mapeamento_laboratorio-main/professor/forms.py
from django import forms
from salas.models import Salas, Reservas
from materiais.models import Materiais, Reserva
from usuarios.models import Usuario
from .validators import validate_date_not_past
from django.utils import timezone



class RealizarReservas(forms.ModelForm):
    class Meta:
        model = Reservas
        fields = "__all__"
        widgets = {
            'data_reserva': forms.DateTimeInput(format='%d/%m/%Y %H:%M', attrs={'type': 'datetime-local'}),
            'data_devolucao': forms.DateTimeInput(format='%d/%m/%Y %H:%M', attrs={'type': 'datetime-local'}),
            'data_solicitacao': forms.HiddenInput(),
        }
        labels = {
            'data_reserva': 'Data de Reserva',
            'data_devolucao': 'Data de Devolução',
            'data_solicitacao': 'Data de Solicitação',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['usuarios'].widget = forms.HiddenInput()
        self.fields['data_reserva'].validators.append(validate_date_not_past)
        self.fields['data_devolucao'].validators.append(validate_date_not_past)

class RealizarReserva(forms.ModelForm):
    class Meta:
        model = Reserva
        fields = "__all__"
        widgets = {
            'data_reserva': forms.DateTimeInput(format='%d/%m/%Y %H:%M', attrs={'type': 'datetime-local'}),
            'data_devolucao': forms.DateTimeInput(format='%d/%m/%Y %H:%M', attrs={'type': 'datetime-local'}),
            'data_solicitacao': forms.HiddenInput(),
        }
        labels = {
            'data_reserva': 'Data de Reserva',
            'data_devolucao': 'Data de Devolução',
            'data_solicitacao': 'Data de Solicitação',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['usuarios'].widget = forms.HiddenInput()
        self.fields['data_reserva'].validators.append(validate_date_not_past)
        self.fields['data_devolucao'].validators.append(validate_date_not_past)

Sistema_mapeamento_laboratorio-main/professor/views.py
# Importando as bibliotecas necessárias
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from usuarios.models import Usuario
from salas.models import Reservas
from materiais.models import Reserva
from .forms import RealizarReservas
from .forms import RealizarReserva
from django.core.exceptions import ValidationError
from django.contrib import messages
from django.utils import timezone



# Função para renderizar a página inicial
def homee(request):
    # Verifica se há um usuário na sessão
    if request.session.get('usuario'):
        try:
            # Obtém o objeto de usuário com base no ID armazenado na sessão
            usuario = Usuario.objects.get(id=request.session['usuario'])

            # Obtém as reservas de salas associadas a esse usuário
            reservas_salas = Reservas.objects.filter(usuarios=usuario)

            # Obtém as reservas de materiais associadas a esse usuário
            reservas_materiais = Reserva.objects.filter(usuarios=usuario)

            form_salas = RealizarReservas()
            form_salas.fields['usuarios'].initial = request.session['usuario']

            form_materiais = RealizarReserva()
            form_materiais.fields['usuarios'].initial = request.session['usuario']
            

            # Renderiza a página inicial com as informações de reservas e o objeto de usuário
            return render(request, 'homee.html', {
                'ReservasSalas': reservas_salas,
                'ReservasMateriais': reservas_materiais,
                'usuario_logado': usuario,
                'form_salas': form_salas,
                'form_materiais': form_materiais,
                'usuario': usuario,
                'nome_usuario': usuario.nome,
            })

        except Usuario.DoesNotExist:
            # Trata o caso em que o usuário não existe
            messages.error(request, 'Usuário não encontrado.')
            return render(request, 'error.html', {'message': 'Usuário não existe'})
    else:
        # Redireciona para a página de login se não houver usuário na sessão
        messages.warning(request, 'Faça login para acessar a homee.')
        return redirect('/auth/login/?status=2')


# Função para o professor visualizar as salas
def ver_salas_professor(request, id):
    # Verifica se há um usuário na sessão
    if request.session.get('usuario'):
        # Obtém o ID do usuário na sessão
        usuario_id = request.session.get('usuario')

        # Obtém todas as reservas associadas ao usuário logado e ao ID fornecido
        reservas = Reservas.objects.filter(usuarios_id=usuario_id, id=id)
        form_salas = RealizarReservas()
        form_materiais = RealizarReserva()

        # Verifica se há pelo menos uma reserva pertencente ao usuário logado
        if len(reservas) > 0:
            # Renderiza a página 'ver_salas_professor.html', passando as informações das reservas
            return render(request, 'ver_salas_professor.html', {'Reservas': reservas, 'usuario_logado': request.session.get('usuario'), 'form_salas': form_salas, 'form_materiais': form_materiais})

        else:
            # Se não houver reservas para o usuário logado, retorna uma mensagem de erro
            return HttpResponse('Não há reservas para o usuário logado.')

    else:
        # Se não houver usuário na sessão, redireciona para a página de login
        return redirect('/auth/login/?status=2')


def realizar_reserva_salas(request):
    if request.method == 'POST':
        form_salas = RealizarReservas(request.POST)
        if form_salas.is_valid():
            form_salas.save()
            return redirect('/professor/reserva_sucesso/')
        else:
            # Adiciona uma mensagem de erro ao framework de mensagens
            messages.error(request, 'Dados inválidos. Por favor, tente novamente.')
            # Redireciona para a página principal
            return redirect('/professor/reserva_dados_invalidos/')
    else:
        form_salas = RealizarReservas()

    # Renderiza a página com o formulário
    return render(request, 'homee.html', {'form': form_salas})


# Função para o professor visualizar os materiais
def ver_materiais_professor(request, id):
    # Verifica se há um usuário na sessão
    if request.session.get('usuario'):
        # Obtém o ID do usuário na sessão
        usuario_id = request.session.get('usuario')

        # Obtém todas as reservas associadas ao usuário logado e ao ID fornecido
        reserva = Reserva.objects.filter(usuarios_id=usuario_id, id=id)
        form_materiais = RealizarReserva()
        form_salas = RealizarReservas()
        # Verifica se há pelo menos uma reserva pertencente ao usuário logado
        if len(reserva) > 0:
            # Renderiza a página 'ver_materiais_professor.html', passando as informações das reservas
            return render(request, 'ver_materiais_professor.html', {'Reserva': reserva, 'usuario_logado': request.session.get('usuario'), 'form_materiais': form_materiais, 'form_salas': form_salas})

        else:
            # Se não houver reservas para o usuário logado, retorna uma mensagem de erro
            return HttpResponse('Não há reservas para o usuário logado.')

    else:
        # Se não houver usuário na sessão, redireciona para a página de login
        return redirect('/auth/login/?status=2')

# Função para realizar a reserva de materiais
def realizar_reserva_materiais(request):
    if request.method == 'POST':
        form_materiais = RealizarReserva(request.POST)
        if form_materiais.is_valid():
            form_materiais.save()
            return redirect('/professor/reserva_sucesso/')
        else:
            # Adiciona uma mensagem de erro ao framework de mensagens
            messages.error(request, 'Dados inválidos. Por favor, tente novamente.')
            # Redireciona para a página principal
            return redirect('/professor/reserva_dados_invalidos/')
    else:
        form_materiais = RealizarReserva()

    # Renderiza a página com o formulário
    return render(request, 'homee.html', {'form': form_materiais})


def reserva_sucesso(request):
    # Renderiza a página de sucesso com o botão para a tela inicial
    return render(request, 'reserva_sucesso.html')

def reserva_dados_invalidos(request):
    # Renderiza a página de sucesso com o botão para a tela inicial
    return render(request, 'reserva_dados_invalidos.html')

Sistema_mapeamento_laboratorio-main/professor/templates/homee.html
{% extends 'base.html' %}

{% block 'titulo' %}Home{% endblock %}

{% block 'conteudo' %}
{% load %}
<div class="container">
    <br>
    <br>

    <h1 class="display-4">Reserva de Salas e Materiais
        <hr style="display: block;">
    </h1>

    <p class="lead">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house"
            viewBox="0 0 16 16">
            <path
                d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5ZM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5 5 5Z" />
        </svg>
        Olá, seja bem vindo, você está logado como PROFESSOR!
    </p>

    <div class="container">
        <div class="row">
            <!-- Coluna para as reservas de Salas -->
            <div class="col-md-6">
                {% for reserva in ReservasSalas %}
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">{{ reserva.salas }}</h5>
                        <p class="card-text">Data devolução: <span class="text-muted">{{ reserva.data_devolucao }}</span></p>
                        <a href="{% url 'professor:ver_salas_professor' reserva.id %}" class="btn btn-primary">Detalhes</a>
                    </div>
                </div>
                {% endfor %}
            </div>
    
            <!-- Coluna para as reservas de Materiais -->
            <div class="col-md-6">
                {% for reserva in ReservasMateriais %}
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">{{ reserva.materiais }}</h5>
                        <p class="card-text">Data devolução: <span class="text-muted">{{ reserva.data_devolucao }}</span></p>
                        <a href="{% url 'professor:ver_materiais_professor' reserva.id %}" class="btn btn-primary">Detalhes</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
<br>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
{% endblock %}

Sistema_mapeamento_laboratorio-main/professor/templates/reserva_dados_invalidos.html
{% extends 'base.html' %}

{% block 'titulo' %}dados invalidos{% endblock %}

{% block 'conteudo' %}
{% load %}

{% if messages %}
<div class="alert alert-danger" role="alert">
    {% for message in messages %}
    <p>{{ message }}</p>
    {% endfor %}
</div>
{% endif %}
<div class="container">
    <br>
    <br>

    <!-- Título da Página -->
    <h1 class="display-4">Insira uma data válida!

    </h1>

    <br>
    <br>
    <!-- Exibição das Salas -->
    <div class="container">
        <div class="row">
            <div class="col-md">

                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <a href="{% url 'professor:homee' %}" class="btn btn-primary">Ir para tela inicial</a>
                    </div>
                </div>

            </div>

        </div>
    </div>

    <br>

</div>
<br>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
{% endblock %}

Sistema_mapeamento_laboratorio-main/professor/templates/reserva_sucesso.html
{% extends 'base.html' %}

{% block 'titulo' %}Home{% endblock %}

{% block 'conteudo' %}
{% load %}
<div class="container">
    <br>
    <br>

    <!-- Título da Página -->
    <h1 class="display-4">Reserva realizada com sucesso!

    </h1>

    <br>
    <br>
    <!-- Exibição das Salas -->
    <div class="container">
        <div class="row">
            <div class="col-md">

                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <a href="{% url 'professor:homee' %}" class="btn btn-primary">Ir para tela inicial</a>
                    </div>
                </div>

            </div>

        </div>
    </div>

    <br>

</div>
<br>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
{% endblock %}

Sistema_mapeamento_laboratorio-main/professor/templates/ver_materiais_professor.html
{% extends 'base.html' %}

{% block 'conteudo' %}

<div class="container">
    <br>
    <div class="row">
        <!-- Coluna para os detalhes do Material -->
        <div class="col-md-6">
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title" style="font-weight: bold; color: black;">Material: </h5><span class="card-text" style="font-weight: normal; color: black;"></span>{{ Reserva.0.materiais }}</span>
                    
                    {% for reserva in Reserva %}
                    <p class="card-text" style="font-weight: normal; color: black;">
                        <br><strong>Data da reserva:</strong><br>
                        {{ reserva.data_reserva }}
                    </p>
                    <p class="card-text" style="font-weight: normal; color: black;">
                        <strong>Solicitante:</strong><br>
                        {{ reserva.usuarios }}
                    </p>
                    <p class="card-text" style="font-weight: normal; color: black;">
                        <strong>Data da Devolução:</strong><br>
                        {{ reserva.data_devolucao }}
                    </p>
                    <p class="card-text" style="font-weight: normal; color: black;">
                        <strong>Data da solicitação:</strong><br>
                        {{ reserva.data_solicitacao }}
                    </p>
                    <hr>
                    {% endfor %}
                </div>
            </div>
        </div>

        <!-- Coluna para o histórico de reservas do Material -->
        <!-- <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    Histórico de Reservas
                </div>
                <ul class="list-group list-group-flush">
                    {% for reserva in Reserva %}
                    <li class="list-group-item">
                        <strong>Usuário:</strong> {{ reserva.usuarios }}<br>
                        <strong>Data da reserva:</strong> {{ reserva.data_reserva }}<br>
                        <strong>Data da devolução:</strong> {{ reserva.data_devolucao }}<br>
                        <strong>Data da solicitação:</strong> {{ reserva.data_solicitacao }}
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div> -->

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
{% endblock %}

Sistema_mapeamento_laboratorio-main/professor/templates/ver_salas_professor.html
{% extends 'base.html' %}

{% block 'conteudo' %}

<div class="container">
    <br>
    <div class="row">
        <!-- Coluna para os detalhes da Sala -->
        <div class="col-md-6">
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title" style="font-weight: bold; color: black;">Sala: </h5><span class="card-text" style="font-weight: normal; color: black;">{{ Reservas.0.salas }}</span>
                    
                    {% for reserva in Reservas %}
                    <p class="card-text" style="font-weight: normal; color: black;">
                        <br><strong>Data da reserva:</strong><br>
                        {{ reserva.data_reserva }}
                    </p>
                    <p class="card-text" style="font-weight: normal; color: black;">
                        <strong>Solicitante:</strong><br>
                        {{ reserva.usuarios }}
                    </p>
                    <p class="card-text" style="font-weight: normal; color: black;">
                        <strong>Data da Devolução:</strong><br>
                        {{ reserva.data_devolucao }}
                    </p>
                    <p class="card-text" style="font-weight: normal; color: black;">
                        <strong>Data da solicitação:</strong><br>
                        {{ reserva.data_solicitacao }}
                    </p>
                    <hr>
                    {% endfor %}
                </div>
            </div>
        </div>

        <!-- Coluna para o histórico de reservas da Sala -->
        <!-- <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    Histórico de Reservas
                </div>
                <ul class="list-group list-group-flush">
                    {% for reserva in Reservas %}
                    <li class="list-group-item">
                        <strong>Usuário:</strong> {{ reserva.usuarios }}<br>
                        <strong>Data da reserva:</strong> {{ reserva.data_reserva }}<br>
                        <strong>Data da devolução:</strong> {{ reserva.data_devolucao }}<br>
                        <strong>Data da solicitação:</strong> {{ reserva.data_solicitacao }}
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div> -->

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
{% endblock %}