Sistema_mapeamento_laboratorio-main/gestor/urls.py
from django.urls import path
from . import views
from .views import calendario_reservas
from .views import calendario_reservas_materiais
from .views import reservas_materiais
from .views import reservas_salas
from .views import SalaListView, SalaCreateView, SalaUpdateView, SalaDetailView, SalaDeleteView
from .views import MaterialListView, MaterialCreateView, MaterialUpdateView, MaterialDetailView, MaterialDeleteView



app_name = 'gestor'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('gestor_ver_salas/', views.gestor_ver_salas, name='gestor_ver_salas'),
    path('gestor_ver_materiais/', views.gestor_ver_materiais, name='gestor_ver_materiais'),
    path('calendario_reservas/', calendario_reservas, name='calendario_reservas'),
    path('calendario_reservas_materiais/', calendario_reservas_materiais, name='calendario_reservas_materiais'),
    path('reservas_materiais/', reservas_materiais, name='reservas_materiais'),
    path('reservas_salas/', reservas_salas, name='reservas_salas'),
    path('salas/', SalaListView.as_view(), name='sala_list'),
    path('salas/nova/', SalaCreateView.as_view(), name='sala_create'),
    path('salas/<int:pk>/editar/', SalaUpdateView.as_view(), name='sala_edit'),
    path('salas/<int:pk>/detail/', SalaDetailView.as_view(), name='sala_detail'),
    path('salas/<int:pk>/excluir/', SalaDeleteView.as_view(), name='sala_delete'),
     path('materiais/', MaterialListView.as_view(), name='material_list'),
    path('materiais/novo/', MaterialCreateView.as_view(), name='material_create'),
    path('materiais/<int:pk>/editar/', MaterialUpdateView.as_view(), name='material_edit'),
    path('materiais/<int:pk>/detalhes/', MaterialDetailView.as_view(), name='material_detail'),
    path('materiais/<int:pk>/excluir/', MaterialDeleteView.as_view(), name='material_delete')
]

Sistema_mapeamento_laboratorio-main/professor/urls.py
from django.urls import path
from . import views

app_name = 'professor'

urlpatterns = [
    path('homee/', views.homee, name='homee'),
    path('ver_salas_professor/<int:id>', views.ver_salas_professor, name='ver_salas_professor'),
    path('realizar_reserva_salas/', views.realizar_reserva_salas, name='realizar_reserva_salas'),
    path('ver_materiais_professor/<int:id>', views.ver_materiais_professor, name='ver_materiais_professor'),
    path('realizar_reserva_materiais/', views.realizar_reserva_materiais, name='realizar_reserva_materiais'),
    path('reserva_sucesso/', views.reserva_sucesso, name='reserva_sucesso'),
    path('reserva_dados_invalidos/', views.reserva_dados_invalidos, name='reserva_dados_invalidos'),
]

Sistema_mapeamento_laboratorio-main/salas/urls.py
from django.urls import path
from . import views

app_name = 'salas'

urlpatterns = [
    path('home/', views.home, name = 'home')
]

Sistema_mapeamento_laboratorio-main/sistema/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('usuarios.urls')),
    path('professor/', include('professor.urls')),
    path('salas/', include('salas.urls')),
    path('materiais/', include('materiais.urls')),
    path('gestor/', include('gestor.urls')),
]

Sistema_mapeamento_laboratorio-main/templates/base.html
<!doctype html>
<html lang="pt-BR">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    {% block 'head' %} {% endblock %}
    <title>{% block 'titulo' %} {% endblock %}</title>
    {% load static %}
</head>

<body>

    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand d-flex align-items-center" href="#">
                <img src="{% static 'img/ufrpe.png' %}" width="100" height="100" class="d-inline-block align-top"
                    alt="">
                <span class="ms-2">UFRPE - Unidade Acadêmica de Belo Jardim</span>
            </a>
            {% if usuario_logado %}
            <div class="d-flex">
                <a href="{% url 'professor:homee' %}" class="btn btn-secondary ms-2">Home</a>
                <button type="button" class="btn btn-primary ms-2" data-bs-toggle="modal"
                    data-bs-target="#exampleModal">
                    Nova reserva
                </button>
                <a href="{% url 'sair' %}" class="btn btn-danger ms-2">Sair</a>
            </div>
            {% endif %}
            {% if usuario_logado2 %}
            <div class="d-flex">
                <a href="{% url 'gestor:home' %}" class="btn btn-secondary ms-2">Home</a>
                <a href="{% url 'sair' %}" class="btn btn-danger ms-2">Sair</a>
            </div>
            {% endif %}
        </div>
    </nav>
    {% block 'conteudo' %} {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    {% if usuario_logado %}
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Realizar uma nova reserva</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button>
                </div>

                <div class="modal-body">

                    <button style="margin-left: 100px" ; onclick="mostrar_form(1)" class="btn btn-info"> Salas </button>
                    <button style="margin-left: 100px" ; onclick="mostrar_form(2)" class="btn btn-warning"> Materiais
                    </button>

                    <br>
                    <hr>

                    <div style="display: none;" id="reservar_salas">
                        <form action="{%url 'professor:realizar_reserva_salas' %}" method="POST">{% csrf_token %}

                            <table>
                                {{form_salas.as_table}}
                            </table>
                            <br>
                            <input type="submit" class="btn btn-success" value="Reservar Sala">
                        </form>
                    </div>

                    <div style="display: none;" id="reservar_materiais">
                        <form action="{%url 'professor:realizar_reserva_materiais' %}" method="POST">{% csrf_token %}

                            <table>
                                {{form_materiais.as_table}}
                            </table>
                            <br>
                            <input type="submit" class="btn btn-success" value="Reservar Material">
                        </form>
                    </div>
                </div>


            </div>
        </div>
    </div>
    {% endif %}
    <script>
        function mostrar_form(v1) {
            reservar_salas = document.getElementById('reservar_salas')
            reservar_materiais = document.getElementById('reservar_materiais')

            if (v1 == 1) {
                reservar_salas.style.display = 'block';
                reservar_materiais.style.display = 'none';
            } else if (v1 == 2) {
                reservar_materiais.style.display = 'block';
                reservar_salas.style.display = 'none';
            }
        }
    </script>
</body>

</html>